<?php
/**
 * Staging bar partial script
 *
 * This script will be injected just after the starting <body> tag in the response.
 */

$this->plugin('translate')->setTranslatorTextDomain('staging_bar');
?>

<style>
    .staging-bar {
        position: fixed;
        top: 0;
        left: 0;
        display: inline-block;
        width: 100%;
        z-index: 2;
        height: 40px;
        padding: 5px 10px;
        background-color: #222;
        color: white;
        border-bottom: 1px solid white;
        font-size: .9em;
    }

    .staging-bar a {
        color: white;
        text-decoration: underline;
    }

    .staging-bar + * {
        margin-top: 40px;
    }
</style>

<div class="staging-bar">
    <span><?= $this->translate('This is the testing website. Please note this site is for testing purposes only! If you want to update your website, visit your public website.')?></span>

    <? if (isset($productionUrl)):?>
        <span><a href="<?= $productionUrl?>"><?= $this->translate('Visit public site.')?></a></span>
    <? endif ?>
</div>